language: python

python: 
  - "3.6"

env:
  global: 
    - SECRET_KEY=$SECRET_KEY

services:
  - docker

before_install:
  - cd backend

before_script: 
  - pip install docker-compose

script: 
  - docker-compose run web sh -c "python manage.py test"