version: '3'

services:
  web:
    depends_on:
      - db
    restart: always
    environment:
      - SECRET_KEY=$SECRET_KEY
    build: .
    volumes:
      - migrations:/app/api/migrations
    ports:
      - "80:8000"
  db:
    image: postgres:11
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
  migrations: